// Passive Tree window: a Path-of-Exile style web of nodes drawn on a canvas.
// The tree itself (positions, names, descriptions) is client/tree-data.js, generated by tools/build-tree.js.
// What the character has allocated lives on the server; this window asks npc/passive_tree.txt through
// api.server.request('passive', ...) and draws the answer:
//   status|message|start|points|mult|refund|ids|sockets|inventory cards|cards on|socket price|choices|job line|...
//   |skill points setting|collected|spent|renewal server|learned skills (id:level,...)
// The Skills tab spends the skill points (collected on the tree's outer ring): "slearn <skill id> <level>" learns a skill of any class.

import { TREE } from './tree-data.js';
import { SKILLS, SKILL_GROUPS } from './skill-data.js';

const NODES = new Map(TREE.nodes.map(n => [n.id, n]));
const ADJ = new Map(TREE.nodes.map(n => [n.id, []]));
for (const [a, b] of TREE.edges) { ADJ.get(a).push(b); ADJ.get(b).push(a); }
const SECTOR_OF_START = new Map(TREE.sectors.map(s => [s.start, s]));
const ORIGIN_COLOR = id => SECTOR_OF_START.get(id)?.color || '#d8d8d8';
const ORIGIN_LETTER = id => (SECTOR_OF_START.get(id)?.name || 'Wanderer')[0];
const KIND = { o: 'Origin', s: 'Passive', n: 'Notable Passive', k: 'Keystone', j: 'Card Socket', m: 'Mastery (choose one)', p: 'Teleport', q: 'Skill Point' };
const RADIUS = { o: 15, s: 6, n: 10, k: 15, j: 11, m: 12, p: 12, q: 13 };

const STYLE = `
/* the game's own cursor, not the system one (the game hides the native cursor inside every component the same way) */
:host-context(.custom-cursor) * { cursor: none !important; }
.pt, .treepane { display: flex; flex-direction: column; height: 100%; background: #0c0e13; color: #d6d9e0; font: 12px Tahoma, Verdana, sans-serif; user-select: none; }
.treepane { flex: 1; min-height: 0; height: auto; }
.treepane[hidden], .etcpane[hidden] { display: none !important; }
.tabs { display: flex; gap: 2px; padding: 4px 8px 0; background: #10131a; border-bottom: 1px solid #2a3040; }
.tabs button { font: inherit; padding: 4px 16px; color: #8a93a8; background: #181d28; border: 1px solid #2a3040; border-bottom: 0; border-radius: 4px 4px 0 0; }
.tabs button:hover { color: #d6d9e0; }
.tabs button.on { color: #f0c860; background: #0c0e13; border-color: #3a4358; }
.etcpane { flex: 1; min-height: 0; display: flex; flex-direction: column; }
.etchead { display: flex; flex-wrap: wrap; align-items: center; gap: 6px 14px; padding: 10px 12px; background: #151922; border-bottom: 1px solid #2a3040; }
.etchead b { color: #f0c860; }
.etchead .big { font-size: 15px; }
.etchead button, .srow button { font: inherit; padding: 3px 10px; color: #d6d9e0; background: #232a38; border: 1px solid #3a4358; border-radius: 3px; }
.etchead button:hover, .srow button:hover { background: #2d364a; }
.etchead button.go { background: #6b4f12; border-color: #f0c860; color: #fff3c0; }
.etchead button.go:hover { background: #7d5c16; }
.srow button[disabled] { opacity: .35; pointer-events: none; }
.etcnote { padding: 8px 12px; color: #8a93a8; border-bottom: 1px solid #1c2230; }
.etcbar { display: flex; flex-wrap: wrap; align-items: center; gap: 6px 12px; padding: 8px 12px; border-bottom: 1px solid #2a3040; }
.etcbar select { font: inherit; padding: 3px 6px; color: #e8ecf5; background: #0c0e13; border: 1px solid #3a4358; border-radius: 3px; }
.etcbar label { color: #aab; }
.skills { flex: 1; min-height: 0; overflow: auto; }
.srow { display: flex; align-items: center; gap: 10px; padding: 5px 12px; border-bottom: 1px solid #1c2230; }
.srow:hover { background: #151b28; }
.srow .sname { flex: 1; min-width: 0; color: #e8ecf5; }
.srow .sname small { display: block; color: #8a93a8; }
.srow .slv { width: 84px; text-align: right; color: #8a93a8; }
.srow.got .slv, .srow.got .sname { color: #9fe08f; }
.skills .none { padding: 12px; color: #8a93a8; }
.bar { display: flex; flex-wrap: wrap; align-items: center; gap: 6px 12px; padding: 6px 8px; background: #151922; border-bottom: 1px solid #2a3040; }
.bar b { color: #f0c860; font-size: 13px; }
.bar .grow { flex: 1; }
.bar button { font: inherit; padding: 3px 9px; color: #d6d9e0; background: #232a38; border: 1px solid #3a4358; border-radius: 3px; }
.bar button:hover { background: #2d364a; }
.bar button.on { background: #6b4f12; border-color: #f0c860; color: #fff3c0; }
.bar button.warn { background: #6b1f1f; border-color: #e06060; color: #fff; }
.search { font: inherit; width: 190px; padding: 3px 6px; color: #e8ecf5; background: #0c0e13; border: 1px solid #3a4358; border-radius: 3px; user-select: text; }
.search:focus { outline: none; border-color: #6fd0ff; }
.found { color: #8a93a8; min-width: 54px; }
.stage { position: relative; flex: 1; min-height: 120px; overflow: hidden; display: flex; }
.view { position: relative; flex: 1; min-width: 0; overflow: hidden; }
.side { flex: none; width: 280px; overflow: auto; padding: 8px 10px; background: #10131a; border-left: 1px solid #2a3040; }
.side[hidden] { display: none !important; }
.side h5 { margin: 10px 0 3px; color: #f0c860; font-size: 12px; }
.side h5:first-child { margin-top: 0; }
.side small { color: #8a93a8; font-weight: normal; }
.side .l { padding: 1px 0; color: #8ec8ff; }
.side .l.bad { color: #ff8a8a; }
.side .l.sk { color: #9fe08f; }
.side .l.info { color: #aab; }
.side .none { color: #8a93a8; }
canvas { position: absolute; inset: 0; width: 100%; height: 100%; touch-action: none; }
.tip { position: absolute; z-index: 5; max-width: 290px; padding: 7px 10px; pointer-events: none; background: rgba(10, 12, 18, .96); border: 1px solid #5b6683; border-radius: 4px; box-shadow: 0 2px 10px #000a; }
.tip h4 { margin: 0 0 1px; font-size: 13px; color: #f0c860; }
.tip .kind { color: #8a93a8; font-size: 11px; margin-bottom: 4px; }
.tip .fx { color: #8ec8ff; }
.tip .sk { color: #9fe08f; }
.tip .card { color: #d9a7ff; }
.tip .bad { color: #ff8a8a; }
.tip .info { color: #b4bccd; }
.tip .foot { margin-top: 5px; padding-top: 4px; border-top: 1px solid #2a3040; color: #aab; }
.results { position: absolute; z-index: 6; left: 8px; top: 8px; width: 270px; max-height: 60%; overflow: auto; background: rgba(10, 12, 18, .96); border: 1px solid #3a4358; border-radius: 4px; }
.results .res { padding: 4px 8px; border-bottom: 1px solid #1c2230; }
.results .res:hover, .results .res.cur { background: #1f2a3f; }
.results .res b { color: #f0c860; font-weight: normal; }
.results .res small { display: block; color: #8a93a8; }
.results .none { padding: 8px; color: #8a93a8; }
.picker { position: absolute; z-index: 7; right: 8px; top: 8px; bottom: 8px; width: 310px; display: flex; flex-direction: column; background: rgba(12, 14, 20, .98); border: 1px solid #6b5a96; border-radius: 4px; }
.picker[hidden], .results[hidden], .tip[hidden], .bar [hidden] { display: none !important; }
.picker header { display: flex; align-items: center; gap: 8px; padding: 7px 9px; border-bottom: 1px solid #2a3040; color: #d9a7ff; font-weight: bold; }
.picker header span { flex: 1; }
.picker button { font: inherit; padding: 2px 8px; color: #d6d9e0; background: #232a38; border: 1px solid #3a4358; border-radius: 3px; }
.picker button:hover { background: #2d364a; }
.picker .current { padding: 7px 9px; border-bottom: 1px solid #2a3040; }
.picker .list { flex: 1; overflow: auto; }
.picker .card { display: flex; gap: 8px; padding: 6px 9px; border-bottom: 1px solid #1c2230; }
.picker .card:hover { background: #1f2a3f; }
.picker .card img { width: 24px; height: 24px; image-rendering: pixelated; flex: none; }
.picker .card b { color: #e8ecf5; font-weight: normal; }
.picker .card small { display: block; color: #8a93a8; white-space: normal; }
.picker .empty { padding: 10px 9px; color: #8a93a8; }
.slotbar { display: flex; flex-wrap: wrap; align-items: center; gap: 6px; padding: 4px 8px; background: #12161e; border-bottom: 1px solid #2a3040; }
.slotbar[hidden], .buildbox[hidden] { display: none !important; }
.slotbar span { color: #8a93a8; }
.slotbar button { font: inherit; padding: 2px 9px; color: #d6d9e0; background: #232a38; border: 1px solid #3a4358; border-radius: 3px; }
.slotbar button:hover { background: #2d364a; }
.slotbar button.cur { border-color: #f0c860; color: #fff3c0; }
.slotbar button.empty { color: #6b7488; }
.slotbar button.old { border-color: #7a3a3a; }
.buildbox { position: absolute; z-index: 8; left: 8px; top: 8px; width: 300px; background: rgba(12, 14, 20, .98); border: 1px solid #5b7a96; border-radius: 4px; }
.buildbox header { display: flex; align-items: center; gap: 8px; padding: 7px 9px; border-bottom: 1px solid #2a3040; color: #8ec8ff; font-weight: bold; }
.buildbox header span { flex: 1; }
.buildbox .current { padding: 8px 9px; border-bottom: 1px solid #2a3040; }
.buildbox .current .bad { color: #ff8a8a; margin-top: 4px; }
.buildbox .bname { font: inherit; width: 100%; box-sizing: border-box; padding: 3px 6px; color: #e8ecf5; background: #0c0e13; border: 1px solid #3a4358; border-radius: 3px; user-select: text; }
.buildbox .acts { display: flex; flex-direction: column; gap: 5px; padding: 8px 9px; }
.buildbox .note { padding: 0 9px 9px; color: #8a93a8; font-size: 11px; }
.buildbox button { font: inherit; padding: 3px 9px; color: #d6d9e0; background: #232a38; border: 1px solid #3a4358; border-radius: 3px; }
.buildbox button:hover { background: #2d364a; }
.buildbox button.warn { background: #6b1f1f; border-color: #e06060; color: #fff; }
.msg { padding: 4px 8px; min-height: 16px; background: #151922; border-top: 1px solid #2a3040; color: #98a2b8; }
.msg.err { color: #ff8a8a; }
.launcher { position: fixed; right: 192px; top: 66px; width: 43px; height: 22px; z-index: 8999; font: bold 11px Tahoma, sans-serif; padding: 0;
  border: 1px solid #6b7a99; border-radius: 4px; background: linear-gradient(#f3f6fd, #d3dbef); color: #273256; display: none; }
.launcher.ingame { display: block; }
`;

const escape = text => String(text).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

/** The server's answer. Null when it is not one. */
export function parseReply(text) {
	const f = String(text || '').split('|');
	if (f.length < 7) return null;
	const pairs = list => (list || '').split(',').filter(Boolean).map(p => p.split(':').map(Number));
	return {
		ok: f[0] === 'ok', message: f[1], start: Number(f[2]) || 0, cap: Number(f[3]) || 0,
		mult: Number(f[4]) || 100, refund: Number(f[5]), ids: f[6].split(',').filter(Boolean).map(Number),
		sockets: pairs(f[7]), inv: pairs(f[8]), cardsOn: f[9] === '1', socketZeny: Number(f[10]) || 0,
		choices: pairs(f[11]), line: Number(f[12]) || 0, keyLimit: Number(f[13]) || 0, upper: f[14] === '1', dropCap: Number(f[15]) || 0,
		builds: (f[16] || '').split(',').filter(Boolean).map(e => { if (e === '-') return null; const [name, count, ok] = e.split(':'); return { name, count: Number(count) || 0, ok: ok === '1' }; }),
		slot: Number(f[17]) || 0, swapZeny: Number(f[18]) || 0,
		skillSetting: Number(f[19]) || 0, skillCollected: Number(f[20]) || 0, skillSpent: Number(f[21]) || 0, renewal: f[22] === '1', learned: pairs(f[23]),
	};
}

/** One effect line with the server's value multiplier applied the way the server applies it. */
export function effectText(fx, mult) {
	const magnitude = Math.max(1, Math.trunc((mult * Math.abs(fx.v) * fx.m + 50) / 100));
	const shown = fx.v === 0 ? 0 : magnitude / fx.m;
	return fx.t.replace('{s}', fx.v < 0 ? '-' : '+').replace('{v}', fmt(shown));
}
const fmt = n => String(+Math.abs(n).toFixed(2));

/** Everything a search can match on one node, lower case. */
function searchText(node) {
	const parts = [node.n, KIND[node.t], node.info || ''];
	for (const fx of node.fx) parts.push(effectText(fx, 100));
	for (const o of node.opts || []) parts.push(o.n, ...o.fx.map(fx => effectText(fx, 100)));
	if (node.req) parts.push(`job line ${node.req} ascendancy`, node.up ? `rebirth reborn ${node.ul}` : '');
	if (node.rs) parts.push(`requires ${node.rs}`);
	if (node.t === 'm') parts.push('mastery choose option');
	if (node.t === 'o') parts.push('origin start class', SECTOR_OF_START.get(node.id)?.name || 'wanderer');
	if (node.t === 'j') parts.push('socket jewel card slot');
	if (node.t === 'p') parts.push('teleport portal rift gate');
	if (node.t === 'q') parts.push('skill point skills learn');
	let text = parts.join(' | ').toLowerCase();
	// names players use for the same thing
	if (text.includes('item appraisal')) text += ' identify';
	if (text.includes('shadow')) text += ' dark';
	if (text.includes('demi-human')) text += ' human demihuman';
	if (text.includes('resistance')) text += ' resist';
	if (text.includes('damage to')) text += ' vs versus against';
	return text;
}
const SKILL_BY_ID = new Map(SKILLS.map(s => [s[0], s]));
const HAY = new Map(TREE.nodes.map(n => [n.id, searchText(n)]));

export default function init(parameters, api) {
	if (api?.version !== 1) throw new Error('path-of-ragnarok requires client API 1');

	const win = api.ui.window({ id: 'path-of-ragnarok', title: 'Path of Ragnarok', width: 920, height: 680, resizable: true });
	const body = win.body;
	body.style.cssText = 'width:100%;height:100%;overflow:hidden';
	body.innerHTML = `<style>${STYLE}</style>
		<div class="pt">
			<div class="tabs"><button class="on" data-tab="tree">Passive Tree</button><button data-tab="etc" title="Spend skill points: learn any skill of any class">Skills</button></div>
			<div class="treepane">
			<div class="bar">
				<span>Passive points: <b class="pts">-</b></span><span class="origin"></span>
				<input class="search" placeholder="Search passives..." autocomplete="off" spellcheck="false"><span class="found"></span>
				<span class="grow"></span>
				<button class="mode" title="While on, a click refunds an allocated node (right-click always does)">Refund mode</button>
				<button class="reset">Reset all</button><button class="fit">Center</button><button class="sidebtn on" title="Show or hide the list of everything your passives give you">Active effects</button>
			</div>
			<div class="slotbar" hidden></div>
			<div class="stage"><div class="view"><canvas></canvas><div class="results" hidden></div><div class="picker" hidden></div><div class="buildbox" hidden></div><div class="tip" hidden></div></div><aside class="side"></aside></div>
				</div>
				<div class="etcpane" hidden></div>
				<div class="msg"></div>
		</div>`;
	const $ = sel => body.querySelector(sel);
	const canvas = $('canvas');
	const ctx = canvas.getContext('2d');
	const tip = $('.tip');
	const side = $('.side');
	const msg = $('.msg');
	const searchBox = $('.search');
	const resultsBox = $('.results');
	const picker = $('.picker');
	const HINT = 'Click a node to allocate it (the whole path to it). Right-click an allocated node to refund it. Drag to move, wheel to zoom.';

	// ---- state ----
	const state = { start: 0, cap: 0, mult: 100, refund: -1, alloc: new Set(), sockets: new Map(), choices: new Map(), line: 0, upper: false, dropCap: 0, builds: [], slot: 0, swapZeny: 0, keyLimit: 0, inv: [], cardsOn: false, socketZeny: 0, loaded: false,
			skillSetting: 0, skillCollected: 0, skillSpent: 0, renewal: false, learned: [] };
	const lineName = () => TREE.lines[state.line] || '';
	const view = { x: 0, y: 0, zoom: 0.4, w: 300, h: 300, dpr: 1 };
	let hover = 0, path = [], refundMode = false, busy = false, dragging = null, resetArmed = 0;
	let matches = [], matchSet = new Set(), cursor = -1, pickerNode = 0;

	const owned = id => id === state.start || state.alloc.has(id);
	/** Nodes this character may never take: another job line's branch, the centre gateways unless Wanderer. */
	const blocked = id => { const n = NODES.get(id); return !!((n.req && (n.req !== lineName() || (n.up && !state.upper))) || (n.w && state.start !== 7)); };
	const unspent = () => Math.max(0, state.cap - state.alloc.size);
	const keystonesUsed = () => [...state.alloc].filter(id => NODES.get(id).t === 'k').length;
	const item = id => api.items?.get?.(id);
	const cardName = id => item(id)?.name || `Card #${id}`;
	const shortText = (text, n = 150) => { const t = String(text || '').replace(/\^[0-9a-fA-F]{6}/g, '').replace(/\s+/g, ' ').trim(); return t.length > n ? `${t.slice(0, n)}...` : t; };

	/** Shortest chain of unallocated nodes from anything owned to `target`, or null. */
	function pathTo(target) {
		if (!state.start || owned(target) || blocked(target)) return null;
		const prev = new Map();
		const queue = [];
		for (const id of [state.start, ...state.alloc]) { prev.set(id, 0); queue.push(id); }
		for (let i = 0; i < queue.length; i++) {
			const id = queue[i];
			if (id === target) break;
			for (const next of ADJ.get(id)) if (!prev.has(next) && !blocked(next)) { prev.set(next, id); queue.push(next); }
		}
		if (!prev.has(target)) return null;
		const out = [];
		for (let id = target; id && !owned(id); id = prev.get(id)) out.push(id);
		return out.reverse();
	}

	/** Can `id` be taken back without cutting other nodes off from the start? */
	function removable(id) {
		if (!state.alloc.has(id)) return false;
		const seen = new Set([state.start]);
		const queue = [state.start];
		for (let i = 0; i < queue.length; i++) {
			for (const next of ADJ.get(queue[i])) {
				if (next !== id && state.alloc.has(next) && !seen.has(next)) { seen.add(next); queue.push(next); }
			}
		}
		for (const a of state.alloc) if (a !== id && !seen.has(a)) return false;
		return true;
	}

	// ---- the list of everything that is active ----
	/** Value of one effect after the bonus-strength setting, the way the server rounds it, signed. */
	const fxValue = fx => (fx.v === 0 ? 0 : Math.sign(fx.v) * Math.max(1, Math.trunc((state.mult * Math.abs(fx.v) * fx.m + 50) / 100)) / fx.m);
	function renderSide() {
		if (side.hidden) return;
		if (!state.start) { side.innerHTML = '<h5>Active effects</h5><div class="none">Choose a first class to wake the tree.</div>'; return; }
		const totals = new Map(), cards = [], picks = [];
		const add = fx => {
			const entry = totals.get(fx.t) || { t: fx.t, v: 0, flag: fx.v === 0 };
			entry.v += fxValue(fx);
			totals.set(fx.t, entry);
		};
		for (const id of [state.start, ...state.alloc]) {
			const node = NODES.get(id);
			node.fx.forEach(add);
			if (node.t === 'm' && state.choices.has(id)) {
				const option = node.opts[state.choices.get(id) - 1];
				if (option) { picks.push(`${node.n}: ${option.n}`); option.fx.forEach(add); }
			}
			if (node.t === 'j' && state.sockets.has(id)) cards.push(state.sockets.get(id));
		}
		const lines = [...totals.values()].filter(e => e.flag || Math.abs(e.v) > 1e-9).map(e => {
			let text = e.t.replace('{s}', e.v < 0 ? '-' : '+').replace('{v}', fmt(e.v));
			if (e.t.includes('monster item drop rate')) {
				const applied = Math.floor(Math.min(e.v, state.dropCap) + 1e-9);
				text += ` - applied: ${applied}% (whole percents only, capped at ${state.dropCap}%)`;
			}
			return { text, bad: !e.flag && e.v < 0, key: text.replace(/^[+-]/, '').toLowerCase() };
		}).sort((a, b) => (a.key < b.key ? -1 : 1));
		const part = (title, rows) => (rows.length ? `<h5>${title}</h5>${rows.join('')}` : '');
		side.innerHTML = `<h5>Active effects <small>${lines.length} lines from ${state.alloc.size + 1} nodes</small></h5>${lines.length ? lines.map(l => `<div class="l${l.bad ? ' bad' : ''}">${escape(l.text)}</div>`).join('') : '<div class="none">Nothing yet.</div>'}`
			+ part('Skills learned', state.learned.map(([id, lv]) => `<div class="l sk">${escape(SKILL_BY_ID.get(id)?.[1] || `Skill #${id}`)} Lv ${lv}</div>`))
			+ part('Mastery choices', picks.map(p => `<div class="l info">${escape(p)}</div>`))
			+ part('Socketed cards', cards.map(id => `<div class="l info">${escape(cardName(id))}</div>`));
	}

	// ---- server ----
	function apply(reply, withInventory) {
		if (!reply) return;
		state.start = reply.start;
		state.cap = reply.cap;
		state.mult = reply.mult;
		state.refund = reply.refund;
		state.alloc = new Set(reply.ids);
		state.sockets = new Map(reply.sockets);
		state.cardsOn = reply.cardsOn;
		state.socketZeny = reply.socketZeny;
		state.choices = new Map(reply.choices);
		state.line = reply.line;
		state.keyLimit = reply.keyLimit;
		state.upper = reply.upper;
		state.dropCap = reply.dropCap;
		state.builds = reply.builds;
		state.slot = reply.slot;
		state.swapZeny = reply.swapZeny;
		state.skillSetting = reply.skillSetting;
		state.skillCollected = reply.skillCollected;
		state.skillSpent = reply.skillSpent;
		state.renewal = reply.renewal;
		state.learned = reply.learned;
		if (withInventory) state.inv = reply.inv;
		state.loaded = true;
		$('.pts').textContent = state.start ? `${unspent()} unspent  (${state.alloc.size} / ${state.cap} used)${state.keyLimit ? `  -  keystones ${keystonesUsed()} / ${state.keyLimit}` : ''}` : '-';
		const sector = SECTOR_OF_START.get(state.start);
		$('.origin').textContent = state.start ? `Start: ${sector ? `${sector.name} (${sector.stat})` : 'Wanderer (all stats)'}` : '';
		$('.mode').hidden = state.refund < 0;
		$('.reset').hidden = state.refund < 0;
		if (!state.alloc.has(pickerNode)) closePicker();
		else if (!picker.hidden) renderPicker();
		renderSide();
		renderSlots();
		renderEtc();
	}

	function say(text, isError) {
		msg.textContent = text || HINT;
		msg.classList.toggle('err', !!isError);
	}

	async function ask(command) {
		if (busy) return false;
		busy = true;
		let good = false;
		try {
			const reply = parseReply(await api.server.request('passive', command, { timeout: 6000 }));
			if (!reply) say('The server sent something unexpected.', true);
			else { apply(reply, command === 'cards'); say(reply.message, !reply.ok); good = reply.ok; }
		} catch (error) {
			say(`The server did not answer (${error?.message || error}). Is the path-of-ragnarok mod switched on?`, true);
		} finally {
			busy = false;
			if (matches.length) runSearch(false);
			updateHover();
			draw();
		}
		return good;
	}

	// ---- drawing ----
	const toScreen = (x, y) => [view.w / 2 + view.x + x * view.zoom, view.h / 2 + view.y + y * view.zoom];
	const toWorld = (sx, sy) => [(sx - view.w / 2 - view.x) / view.zoom, (sy - view.h / 2 - view.y) / view.zoom];
	const nodeScale = () => Math.max(0.7, Math.min(1.7, view.zoom * 1.5));

	function edgeState(a, b) {
		const oa = owned(a), ob = owned(b);
		if (oa && ob) return 'on';
		if (path.includes(a) && (path.includes(b) || ob || oa)) return 'path';
		if (path.includes(b) && (oa || ob)) return 'path';
		return (oa || ob) ? 'open' : 'off';
	}

	function drawEdge([a, b, shape]) {
		const na = NODES.get(a), nb = NODES.get(b);
		const kind = edgeState(a, b);
		const portal = shape === 2;
		const arc = shape === 1;
		// a teleport link crosses the whole tree: only draw it once it is owned, on a path or hovered
		if (portal && kind === 'off' && hover !== a && hover !== b) return;
		ctx.setLineDash(portal ? [8, 8] : []);
		const afford = path.length <= unspent();
		ctx.lineWidth = (kind === 'on' ? 3.4 : kind === 'path' ? 3 : 2) * Math.max(0.6, Math.min(1.6, view.zoom * 1.4));
		ctx.strokeStyle = kind === 'on' ? '#e8c05a' : kind === 'path' ? (afford ? '#6fd0ff' : '#e06060') : kind === 'open' ? '#4a566e' : '#2c3342';
		ctx.beginPath();
		const [x1, y1] = toScreen(na.x, na.y);
		if (arc) {
			const [cx, cy] = toScreen(0, 0);
			const r = Math.hypot(na.x, na.y) * view.zoom;
			const a1 = Math.atan2(na.y, na.x), a2 = Math.atan2(nb.y, nb.x);
			let d = a2 - a1;
			while (d > Math.PI) d -= 2 * Math.PI;
			while (d < -Math.PI) d += 2 * Math.PI;
			ctx.arc(cx, cy, r, a1, a2, d < 0);
		} else {
			const [x2, y2] = toScreen(nb.x, nb.y);
			ctx.moveTo(x1, y1);
			ctx.lineTo(x2, y2);
		}
		ctx.stroke();
		ctx.setLineDash([]);
	}

	function nodePath(type, x, y, r) {
		ctx.beginPath();
		if (type === 'k') {
			for (let i = 0; i < 6; i++) {
				const a = Math.PI / 6 + i * Math.PI / 3;
				ctx[i ? 'lineTo' : 'moveTo'](x + r * Math.cos(a), y + r * Math.sin(a));
			}
			ctx.closePath();
		} else if (type === 'j') {
			ctx.moveTo(x, y - r * 1.2);
			ctx.lineTo(x + r, y);
			ctx.lineTo(x, y + r * 1.2);
			ctx.lineTo(x - r, y);
			ctx.closePath();
		} else ctx.arc(x, y, r, 0, Math.PI * 2);
	}

	function drawNode(node) {
		const [x, y] = toScreen(node.x, node.y);
		if (x < -40 || y < -40 || x > view.w + 40 || y > view.h + 40) return;
		const z = nodeScale();
		const r = RADIUS[node.t] * z;
		const isOwned = owned(node.id);
		const inPath = path.includes(node.id);
		const afford = path.length <= unspent();
		const reachable = !isOwned && ADJ.get(node.id).some(owned);
		const dim = matchSet.size > 0 && !matchSet.has(node.id);
		const filled = node.t === 'j' && state.sockets.has(node.id);
		let fill = '#222936', stroke = '#4b566a';
		if (node.t === 'o') { fill = '#1a1f2a'; stroke = ORIGIN_COLOR(node.id); }
		if (node.t === 'k') stroke = '#d96a3a';
		if (node.t === 'n') stroke = '#b99a52';
		if (node.t === 'j') stroke = '#a070d0';
		if (node.t === 'm') stroke = '#3fc0a0';
		if (node.t === 'p') stroke = '#8fb8ff';
		if (node.t === 'q') stroke = '#4fd6e8';
		const chosen = node.t === 'm' && state.choices.has(node.id);
		const locked = node.req && (node.req !== lineName() || (node.up && !state.upper));
		if (locked && !isOwned) stroke = '#7a3a3a';
		if (isOwned) { fill = node.t === 'o' ? ORIGIN_COLOR(node.id) : node.t === 'j' ? (filled ? '#8d5fd0' : '#2a2140') : node.t === 'm' ? (chosen ? '#2f9c82' : '#1c3a33') : node.t === 'q' ? '#4fd6e8' : '#e8c05a'; stroke = '#fff0b8'; }
		else if (inPath) { fill = afford ? '#2b6f93' : '#7a2b2b'; stroke = afford ? '#6fd0ff' : '#e06060'; }
		else if (reachable && state.start) stroke = '#6fb4ff';
		ctx.globalAlpha = dim ? 0.25 : 1;
		if (isOwned && node.t === 'o') { ctx.shadowColor = ORIGIN_COLOR(node.id); ctx.shadowBlur = 14; }
		else if (isOwned) { ctx.shadowColor = node.t === 'j' ? '#a070d0' : '#e8c05a'; ctx.shadowBlur = node.t === 'k' ? 16 : 8; }
		nodePath(node.t, x, y, r);
		ctx.fillStyle = fill;
		ctx.fill();
		ctx.shadowBlur = 0;
		ctx.lineWidth = node.t === 's' ? 1.5 : 2.4;
		ctx.strokeStyle = stroke;
		ctx.stroke();
		if (node.t === 'n' || node.t === 'k') {
			nodePath(node.t, x, y, r * 0.55);
			ctx.fillStyle = isOwned ? '#fff0b8' : node.t === 'k' ? '#6a2e1a' : '#3a3220';
			ctx.fill();
		}
		if (node.t === 'm') {
			ctx.lineWidth = 1.6;
			ctx.strokeStyle = isOwned ? '#fff0b8' : '#3fc0a0';
			nodePath('m', x, y, r * 0.62);
			ctx.stroke();
			if (chosen) { nodePath('m', x, y, r * 0.3); ctx.fillStyle = '#d8fff4'; ctx.fill(); }
		}
		if (node.t === 'q') {
			ctx.lineWidth = 1.6;
			ctx.strokeStyle = isOwned ? '#0c3a44' : '#4fd6e8';
			nodePath('q', x, y, r * 0.55);
			ctx.stroke();
			ctx.fillStyle = isOwned ? '#0c3a44' : '#4fd6e8';
			ctx.font = `bold ${Math.round(12 * z)}px Tahoma, sans-serif`;
			ctx.textAlign = 'center';
			ctx.textBaseline = 'middle';
			ctx.fillText('+', x, y + 1);
		}
		if (node.t === 'p') {
			ctx.lineWidth = 1.6;
			ctx.strokeStyle = isOwned ? '#fff0b8' : '#8fb8ff';
			for (const f of [0.68, 0.38]) { nodePath('p', x, y, r * f); ctx.stroke(); }
		}
		if (node.t === 'j' && !isOwned) {
			nodePath('j', x, y, r * 0.5);
			ctx.fillStyle = '#3a2d58';
			ctx.fill();
		}
		if (node.t === 'j' && filled) {
			nodePath('j', x, y, r * 0.45);
			ctx.fillStyle = '#e8d6ff';
			ctx.fill();
		}
		if (node.t === 'o') {
			ctx.fillStyle = isOwned ? '#10131a' : ORIGIN_COLOR(node.id);
			ctx.font = `bold ${Math.round(14 * z)}px Tahoma, sans-serif`;
			ctx.textAlign = 'center';
			ctx.textBaseline = 'middle';
			ctx.fillText(ORIGIN_LETTER(node.id), x, y + 1);
		}
		if (matchSet.has(node.id)) {
			nodePath(node.t, x, y, r + 7);
			ctx.lineWidth = 2.5;
			ctx.strokeStyle = node.id === matches[cursor] ? '#ffffff' : '#6ff0ff';
			ctx.stroke();
		}
		if (node.t === 'p' && hover && NODES.get(hover)?.pt === node.id) {
			nodePath('p', x, y, r + 7);
			ctx.lineWidth = 2.5;
			ctx.strokeStyle = '#8fb8ff';
			ctx.stroke();
		}
		if (node.id === hover) {
			nodePath(node.t, x, y, r + 4);
			ctx.lineWidth = 2;
			ctx.strokeStyle = '#ffffff';
			ctx.stroke();
		}
		ctx.globalAlpha = dim ? 0.25 : 1;
		// keystone, socket and notable names are readable once zoomed in
		if ((node.t === 'k' || node.t === 'j' || node.t === 'm' || node.t === 'q' || (node.t === 'n' && view.zoom > 0.9)) && view.zoom > 0.42) {
			ctx.fillStyle = isOwned ? '#f0c860' : '#8a93a8';
			ctx.font = `${Math.round(11 * Math.min(1.3, view.zoom * 1.3))}px Tahoma, sans-serif`;
			ctx.textAlign = 'center';
			ctx.textBaseline = 'top';
			ctx.fillText(filled ? cardName(state.sockets.get(node.id)) : chosen ? `${node.n}: ${node.opts[state.choices.get(node.id) - 1]?.n || ''}` : node.n, x, y + r + 3);
		}
		ctx.globalAlpha = 1;
	}

	function draw() {
		ctx.setTransform(view.dpr, 0, 0, view.dpr, 0, 0);
		ctx.clearRect(0, 0, view.w, view.h);
		const [cx, cy] = toScreen(0, 0);
		ctx.lineWidth = 1;
		ctx.strokeStyle = '#161b25';
		for (const r of [210, 340, 470, 600, 1020]) { ctx.beginPath(); ctx.arc(cx, cy, r * view.zoom, 0, Math.PI * 2); ctx.stroke(); }
		if (matchSet.size) ctx.globalAlpha = 0.55;
		TREE.edges.forEach(drawEdge);
		ctx.globalAlpha = 1;
		TREE.nodes.forEach(drawNode);
		if (!state.loaded) {
			ctx.fillStyle = '#8a93a8';
			ctx.font = '13px Tahoma, sans-serif';
			ctx.textAlign = 'center';
			ctx.textBaseline = 'middle';
			ctx.fillText('Asking the server...', view.w / 2, view.h / 2);
		}
	}

	function resize() {
		const box = canvas.getBoundingClientRect();
		view.w = Math.max(1, box.width);
		view.h = Math.max(1, box.height);
		view.dpr = window.devicePixelRatio || 1;
		canvas.width = Math.floor(view.w * view.dpr);
		canvas.height = Math.floor(view.h * view.dpr);
		draw();
	}
	function fit() {
		view.x = 0;
		view.y = 0;
		view.zoom = Math.max(0.2, Math.min(1.2, Math.min(view.w, view.h) / 3100));
		draw();
	}
	function focus(id) {
		const node = NODES.get(id);
		if (!node) return;
		view.zoom = Math.max(view.zoom, 0.9);
		view.x = -node.x * view.zoom;
		view.y = -node.y * view.zoom;
		draw();
	}

	// ---- search ----
	function runSearch(jump) {
		const words = searchBox.value.toLowerCase().split(/\s+/).filter(Boolean);
		matches = [];
		if (words.length) {
			for (const node of TREE.nodes) {
				const hay = HAY.get(node.id) + (node.t === 'j' && state.sockets.has(node.id) ? ` ${cardName(state.sockets.get(node.id)).toLowerCase()}` : '');
				if (words.every(w => hay.includes(w))) matches.push(node.id);
			}
			// names first, then keystones/notables/sockets, then the rest
			const rank = n => (words.every(w => n.n.toLowerCase().includes(w)) ? 0 : 2) + ('knj'.includes(n.t) ? 0 : 1);
			matches.sort((a, b) => rank(NODES.get(a)) - rank(NODES.get(b)) || a - b);
		}
		matchSet = new Set(matches);
		cursor = matches.length ? Math.min(Math.max(cursor, 0), matches.length - 1) : -1;
		if (jump) cursor = matches.length ? 0 : -1;
		$('.found').textContent = words.length ? `${matches.length} found` : '';
		renderResults(words.length > 0);
		if (jump && matches.length) focus(matches[0]);
		draw();
	}
	function renderResults(show) {
		resultsBox.hidden = !show;
		if (!show) return;
		resultsBox.innerHTML = matches.length
			? matches.slice(0, 40).map((id, i) => {
				const node = NODES.get(id);
				const first = node.fx[0] ? effectText(node.fx[0], state.mult) : (node.info ? 'Card socket' : '');
				return `<div class="res${i === cursor ? ' cur' : ''}" data-id="${id}"><b>${escape(node.n)}</b> <small>${KIND[node.t]} - ${escape(first)}${owned(id) ? ' - owned' : ''}</small></div>`;
			}).join('') + (matches.length > 40 ? `<div class="none">...and ${matches.length - 40} more (shown on the tree)</div>` : '')
			: '<div class="none">Nothing matches.</div>';
	}
	function step(delta) {
		if (!matches.length) return;
		cursor = (cursor + delta + matches.length) % matches.length;
		focus(matches[cursor]);
		renderResults(true);
	}
	searchBox.addEventListener('input', () => runSearch(true));
	searchBox.addEventListener('keydown', event => {
		event.stopPropagation();
		if (event.key === 'Enter') { event.preventDefault(); step(event.shiftKey ? -1 : 1); }
		else if (event.key === 'Escape') { searchBox.value = ''; runSearch(false); searchBox.blur(); }
	});
	searchBox.addEventListener('keyup', event => event.stopPropagation());
	resultsBox.addEventListener('click', event => {
		const row = event.target.closest('.res');
		if (!row) return;
		cursor = matches.indexOf(Number(row.dataset.id));
		focus(Number(row.dataset.id));
		renderResults(true);
	});

	// ---- card socket picker ----
	function closePicker() { pickerNode = 0; picker.hidden = true; }
	function openPicker(id) {
		const isSocket = NODES.get(id).t === 'j';
		if (isSocket && !state.cardsOn) return say('Card sockets are switched off on this server.', true);
		pickerNode = id;
		picker.hidden = false;
		renderPicker();
		if (isSocket) ask('cards');
	}
	/** The options of a mastery node: pick one, change any time for free. */
	function renderChoices(node) {
		const chosen = state.choices.get(node.id);
		picker.innerHTML = `<header><span>${escape(node.n)}</span><button data-act="close">Close</button></header>
			<div class="current">${chosen ? `Chosen: <b>${escape(node.opts[chosen - 1]?.n || '')}</b>` : 'Nothing chosen yet: the node does nothing until you pick.'}</div>
			<div class="list">${node.opts.map((o, i) => `<div class="card" data-opt="${i + 1}"><div><b>${escape(o.n)}</b>${chosen === i + 1 ? ' (active)' : ''}${o.fx.map(fx => `<small style="color:#8ec8ff">${escape(effectText(fx, state.mult))}</small>`).join('')}</div></div>`).join('')}</div>`;
	}
	function renderPicker() {
		const node = NODES.get(pickerNode);
		if (node.t === 'm') return renderChoices(node);
		const current = state.sockets.get(pickerNode);
		const price = state.socketZeny ? ` (${state.socketZeny.toLocaleString()} zeny)` : '';
		picker.innerHTML = `<header><span>${escape(node.n)}</span><button data-act="close">Close</button></header>
			<div class="current">${current ? `<b>${escape(cardName(current))}</b><small style="display:block;color:#8a93a8">${escape(shortText(item(current)?.description, 220))}</small><div style="margin-top:5px"><button data-act="remove">Take the card out</button></div>`
				: 'Empty. Pick a card below; it leaves your inventory and sits in the socket.'}</div>
			<div class="list">${state.inv.length ? state.inv.map(([id, amount]) => `<div class="card" data-card="${id}"><img data-icon="${id}"><div><b>${escape(cardName(id))}</b>${amount > 1 ? ` x${amount}` : ''}${price}<small>${escape(shortText(item(id)?.description))}</small></div></div>`).join('')
				: '<div class="empty">No card in your inventory can go into a socket.</div>'}</div>`;
		picker.querySelectorAll('img[data-icon]').forEach(async img => { try { const url = await api.items.icon(Number(img.dataset.icon)); if (url) img.src = url; } catch { /* no icon */ } });
	}
	picker.addEventListener('click', async event => {
		const act = event.target.closest('[data-act]')?.dataset.act;
		if (act === 'close') return closePicker();
		if (act === 'remove') { await ask(`unsocket ${pickerNode}`); return; }
		const opt = event.target.closest('[data-opt]');
		if (opt) { await ask(`choose ${pickerNode} ${opt.dataset.opt}`); return; }
		const row = event.target.closest('[data-card]');
		if (row) { const node = pickerNode; if (await ask(`socket ${node} ${row.dataset.card}`)) closePicker(); }
	});

	// ---- saved builds: up to 5 slots to swap between ----
	const slotbar = $('.slotbar');
	const buildbox = $('.buildbox');
	let buildSlot = 0, armed = '';
	const pretty = name => String(name || '').replace(/_/g, ' ');
	const wire = name => String(name || '').trim().replace(/\s+/g, '_').replace(/[^A-Za-z0-9_-]/g, '').slice(0, 16);

	function renderSlots() {
		slotbar.hidden = !state.builds.length;
		if (!state.builds.length) { closeBuild(); return; }
		slotbar.innerHTML = `<span>Builds:</span>${state.builds.map((b, i) => {
			const cls = [state.slot === i + 1 ? 'cur' : '', b ? '' : 'empty', b && !b.ok ? 'old' : ''].filter(Boolean).join(' ');
			return `<button class="${cls}" data-slot="${i + 1}" title="${b ? `${b.count} nodes${b.ok ? '' : ' (older tree layout, cannot be loaded)'}` : 'Empty: click to save the current tree here'}">${i + 1}: ${b ? escape(pretty(b.name)) : 'empty'}${b ? ` (${b.count})` : ''}</button>`;
		}).join('')}`;
		if (buildSlot) renderBuild();
	}
	function closeBuild() { buildSlot = 0; armed = ''; buildbox.hidden = true; }
	function openBuild(slot) { buildSlot = slot; armed = ''; buildbox.hidden = false; renderBuild(); }
	function renderBuild() {
		const b = state.builds[buildSlot - 1];
		const price = state.swapZeny ? ` (${state.swapZeny.toLocaleString()} zeny)` : '';
		const arm = (act, label) => `<button data-act="${act}"${armed === act ? ' class="warn"' : ''}>${armed === act ? 'Click again to confirm' : label}</button>`;
		buildbox.innerHTML = `<header><span>Build slot ${buildSlot}</span><button data-act="close">Close</button></header>
			<div class="current">${b
				? `<b>${escape(pretty(b.name))}</b> - ${b.count} nodes${b.ok ? '' : '<div class="bad">Saved with an older version of the tree: it cannot be loaded, only overwritten or deleted.</div>'}`
				: 'Empty. Saving copies your current tree (nodes, mastery choices and socketed cards) into this slot.'}
				<div style="margin-top:6px"><input class="bname" maxlength="16" placeholder="Name" value="${escape(b ? b.name : `Build_${buildSlot}`).replace(/_/g, ' ')}"></div></div>
			<div class="acts">
				${arm('save', b ? 'Overwrite with the current tree' : 'Save the current tree here')}
				${b && b.ok ? arm('load', `Load this build${price}`) : ''}
				${b ? '<button data-act="rename">Rename</button>' : ''}
				${b ? arm('del', 'Delete') : ''}
			</div>
			<div class="note">Loading puts your socketed cards back in the inventory, replaces the whole tree with the saved one and sockets the saved cards again where you still have them. Nodes you can no longer take are skipped.</div>`;
	}
	slotbar.addEventListener('click', event => {
		const button = event.target.closest('[data-slot]');
		if (button) { const slot = Number(button.dataset.slot); if (buildSlot === slot && !buildbox.hidden) closeBuild(); else openBuild(slot); }
	});
	buildbox.addEventListener('keydown', event => event.stopPropagation());
	buildbox.addEventListener('click', async event => {
		const act = event.target.closest('[data-act]')?.dataset.act;
		if (!act) return;
		if (act === 'close') return closeBuild();
		const slot = buildSlot;
		const name = wire(buildbox.querySelector('.bname')?.value);
		if (act === 'rename') {
			if (!name) return say('Type a name first (letters, digits, - and _).', true);
			await ask(`bname ${slot} ${name}`);
			return renderBuild();
		}
		const needsConfirm = (act === 'save' && state.builds[slot - 1]) || act === 'load' || act === 'del';
		if (needsConfirm && armed !== act) { armed = act; renderBuild(); return; }
		armed = '';
		if (act === 'save') await ask(`bsave ${slot}${name ? ` ${name}` : ''}`);
		else if (act === 'load') await ask(`bload ${slot}`);
		else if (act === 'del') await ask(`bdel ${slot}`);
		renderBuild();
	});

	// ---- the Skills tab: spend skill points, learn any skill of any class ----
	const etcPane = $('.etcpane');
	let tab = 'tree';
	const etcFilter = { group: -1, text: '', learned: false };
	const ETC_ROWS = 150;
	const skillsLeft = () => Math.max(0, state.skillCollected - state.skillSpent);
	const learnedLevel = id => (state.learned.find(([sid]) => sid === id) || [0, 0])[1];
	/** The skills of this server's era: [id, name, max level, group]. */
	const eraSkills = () => SKILLS.map(s => [s[0], s[1], state.renewal ? s[3] : s[2], s[4]]).filter(s => s[2] > 0);

	function renderEtcHead() {
		const head = etcPane.querySelector('.etchead');
		if (!head) return;
		const off = state.loaded && state.skillSetting < 1;
		let html;
		if (!state.loaded) html = '<span class="none">Asking the server...</span>';
		else if (!state.start) html = '<span>Choose a first class to wake the tree.</span>';
		else if (off) html = '<span>Skill points are switched off on this server.</span>';
		else html = `<span>Skill points: <b class="big">${skillsLeft()}</b> left <small>(${state.skillCollected} of ${state.skillSetting} collected, ${state.skillSpent} spent)</small></span>${state.skillCollected < state.skillSetting ? '<small>Collect more on the outer ring of the passive tree: the cyan + nodes, reached from the north, east, south or west.</small>' : ''}`;
		head.innerHTML = html;
	}
	function renderEtcList() {
		const box = etcPane.querySelector('.skills');
		if (!box) return;
		const words = etcFilter.text.toLowerCase().split(/\s+/).filter(Boolean);
		const open = state.start && state.skillCollected > 0;
		const left = skillsLeft();
		let rows = eraSkills().filter(s => {
			if (etcFilter.group >= 0 && s[3] !== etcFilter.group) return false;
			if (etcFilter.learned && !learnedLevel(s[0])) return false;
			const hay = `${s[1]} ${SKILL_GROUPS[s[3]].n}`.toLowerCase();
			return words.every(w => hay.includes(w));
		});
		const total = rows.length;
		// what you learned first, then the catalogue in id order
		rows.sort((a, b) => (learnedLevel(b[0]) > 0) - (learnedLevel(a[0]) > 0) || a[0] - b[0]);
		rows = rows.slice(0, ETC_ROWS);
		box.innerHTML = rows.length
			? rows.map(([id, name, max, group]) => {
				const have = learnedLevel(id);
				const full = have >= max;
				const next = !open || full || left < 1;
				return `<div class="srow${have ? ' got' : ''}"><div class="sname">${escape(name)}<small>${escape(SKILL_GROUPS[group].n)} - max Lv ${max}</small></div>
					<span class="slv">${have ? `Lv ${have} / ${max}` : `- / ${max}`}</span>
					<button data-learn="${id}" data-to="${Math.min(max, have + 1)}"${next ? ' disabled' : ''} title="Learn the next level (1 point)">+1</button>
					<button data-learn="${id}" data-to="${Math.min(max, have + left)}"${next ? ' disabled' : ''} title="Spend all your points on this skill, up to its maximum">Max</button></div>`;
			}).join('') + (total > rows.length ? `<div class="none">${total - rows.length} more: narrow the list with the class filter or the search box.</div>` : '')
			: '<div class="none">No skill matches.</div>';
	}
	function renderEtc() {
		if (tab !== 'etc') return;
		if (!etcPane.querySelector('.skills')) {
			const groups = SKILL_GROUPS.map((g, i) => [i, g]).filter(([, g]) => state.renewal || !g.re);
			etcPane.innerHTML = `<div class="etchead"></div>
				<div class="etcnote">Learn any skill of any class: each level costs one point. Skill points are the cyan + nodes on the outer ring of the passive tree; a point stays yours once collected, and what you learn is permanent. Skills you already have at that level cannot be bought again.</div>
				<div class="etcbar"><select class="sgroup"><option value="-1">All classes</option>${groups.map(([i, g]) => `<option value="${i}">${escape(g.n)}</option>`).join('')}</select>
					<input class="search ssearch" placeholder="Search skills..." autocomplete="off" spellcheck="false" value="${escape(etcFilter.text)}">
					<label><input type="checkbox" class="sknown"${etcFilter.learned ? ' checked' : ''}> Learned only</label></div>
				<div class="skills"></div>`;
			etcPane.querySelector('.sgroup').value = String(etcFilter.group);
		}
		renderEtcHead();
		renderEtcList();
	}
	function setTab(name) {
		tab = name;
		body.querySelectorAll('.tabs [data-tab]').forEach(b => b.classList.toggle('on', b.dataset.tab === name));
		$('.treepane').hidden = name !== 'tree';
		etcPane.hidden = name !== 'etc';
		if (name === 'etc') { etcPane.innerHTML = ''; renderEtc(); ask('state'); }
		else requestAnimationFrame(resize);
	}
	body.querySelector('.tabs').addEventListener('click', event => {
		const b = event.target.closest('[data-tab]');
		if (b && b.dataset.tab !== tab) setTab(b.dataset.tab);
	});
	etcPane.addEventListener('keydown', event => event.stopPropagation());
	etcPane.addEventListener('keyup', event => event.stopPropagation());
	etcPane.addEventListener('input', event => {
		if (event.target.matches('.ssearch')) { etcFilter.text = event.target.value; renderEtcList(); }
	});
	etcPane.addEventListener('change', event => {
		if (event.target.matches('.sgroup')) { etcFilter.group = Number(event.target.value); renderEtcList(); }
		else if (event.target.matches('.sknown')) { etcFilter.learned = event.target.checked; renderEtcList(); }
	});
	etcPane.addEventListener('click', async event => {
		const learn = event.target.closest('[data-learn]');
		if (learn && !learn.disabled) await ask(`slearn ${learn.dataset.learn} ${learn.dataset.to}`);
	});

	// ---- hover, tooltip ----
	function nodeAt(sx, sy) {
		let best = 0, bestD = Infinity;
		const z = nodeScale();
		for (const node of TREE.nodes) {
			const [x, y] = toScreen(node.x, node.y);
			const d = Math.hypot(x - sx, y - sy);
			if (d <= RADIUS[node.t] * z + 4 && d < bestD) { best = node.id; bestD = d; }
		}
		return best;
	}

	function showTip(sx, sy) {
		const node = NODES.get(hover);
		if (!node) { tip.hidden = true; return; }
		const lines = node.fx.map(fx => `<div class="fx${fx.v < 0 ? ' bad' : ''}">${escape(effectText(fx, state.mult))}</div>`);
		if (node.info) lines.push(`<div class="info">${escape(node.info)}</div>`);
		if (node.opts) {
			const chosen = state.choices.get(node.id);
			for (const [i, o] of node.opts.entries()) lines.push(`<div class="${chosen === i + 1 ? 'sk' : 'info'}">${chosen === i + 1 ? '> ' : '- '}${escape(o.n)}: ${escape(o.fx.map(fx => effectText(fx, state.mult)).join(', '))}</div>`);
		}
		if (node.w) lines.push(`<div class="${state.start === 7 ? 'sk' : 'bad'}">Only for the Wanderer start</div>`);
		if (node.req) lines.push(`<div class="${blocked(node.id) ? 'bad' : 'sk'}">Job line: ${escape(node.up ? `${node.ul} (reborn ${node.req})` : node.req)}</div>`);
		if (node.rs) lines.push(`<div class="info">Needs ${escape(node.rs)}</div>`);
		if (node.t === 'j' && state.sockets.has(node.id)) {
			const card = state.sockets.get(node.id);
			lines.push(`<div class="card">Holds: ${escape(cardName(card))}</div><div class="info">${escape(shortText(item(card)?.description, 200))}</div>`);
		}
		let foot = '';
		if (!state.start) foot = 'Choose a first class to wake the tree.';
		else if (node.id === state.start) foot = 'Your starting node. Always active.';
		else if (state.alloc.has(node.id)) {
			const refunding = state.refund < 0 ? 'Allocated.' : removable(node.id)
				? `Right-click to refund${state.refund ? ` (${state.refund.toLocaleString()} zeny)` : ''}.`
				: 'Other nodes depend on this one.';
			foot = node.t === 'j' ? `Click to ${state.sockets.has(node.id) ? 'change the card' : 'insert a card'}. ${state.refund < 0 ? '' : refunding}`
				: node.t === 'm' ? `Click to ${state.choices.has(node.id) ? 'change the option' : 'choose an option'}. ${state.refund < 0 ? '' : refunding}` : `Allocated. ${state.refund < 0 ? '' : refunding}`;
		} else if (path.length && node.t === 'k' && state.keyLimit && keystonesUsed() >= state.keyLimit) {
			foot = `<span class="bad">Keystone limit reached (${keystonesUsed()} / ${state.keyLimit}). Refund one first.</span>`;
		} else if (path.length) {
			foot = path.length > unspent()
				? `<span class="bad">Needs ${path.length} point${path.length > 1 ? 's' : ''}, you have ${unspent()}.</span>`
				: `Click to allocate ${path.length} node${path.length > 1 ? 's' : ''} (${path.length} point${path.length > 1 ? 's' : ''}).`;
		}
		tip.innerHTML = `<h4>${escape(node.n)}</h4><div class="kind">${KIND[node.t]}</div>${lines.join('')}${foot ? `<div class="foot">${foot}</div>` : ''}`;
		tip.hidden = false;
		const box = tip.getBoundingClientRect();
		tip.style.left = `${Math.max(4, Math.min(view.w - box.width - 4, sx + 16))}px`;
		tip.style.top = `${Math.max(4, Math.min(view.h - box.height - 4, sy + 16))}px`;
	}

	let lastPointer = [0, 0];
	function updateHover() {
		const id = nodeAt(lastPointer[0], lastPointer[1]);
		hover = id;
		path = (id && !dragging) ? (pathTo(id) || []) : [];
		showTip(lastPointer[0], lastPointer[1]);
		draw();
	}

	// ---- input ----
	const pointer = event => { const box = canvas.getBoundingClientRect(); return [event.clientX - box.left, event.clientY - box.top]; };

	// Plain mouse events, like the game's own windows use (pointer capture is not needed: the
	// move and release listeners sit on the page while a button is held).
	const onDragMove = event => {
		if (!dragging) return;
		lastPointer = pointer(event);
		const dx = event.clientX - dragging.x, dy = event.clientY - dragging.y;
		if (!dragging.moved && Math.hypot(dx, dy) > 5) { dragging.moved = true; tip.hidden = true; }
		if (dragging.moved) { view.x = dragging.vx + dx; view.y = dragging.vy + dy; draw(); }
	};
	const onRelease = event => {
		const drag = dragging;
		if (!drag) return;
		dragging = null;
		removeEventListener('mousemove', onDragMove, true);
		removeEventListener('mouseup', onRelease, true);
		lastPointer = pointer(event);
		if (drag.moved || drag.button !== 0) { updateHover(); return; }
		const id = nodeAt(lastPointer[0], lastPointer[1]);
		if (!id) return;
		if (state.alloc.has(id) && refundMode) return refundNode(id);
		if (state.alloc.has(id) && 'jm'.includes(NODES.get(id).t)) return openPicker(id);
		allocate(id);
	};
	canvas.addEventListener('mousedown', event => {
		if (event.button !== 0 && event.button !== 1) return;
		event.preventDefault();
		lastPointer = pointer(event);
		dragging = { x: event.clientX, y: event.clientY, vx: view.x, vy: view.y, moved: false, button: event.button };
		addEventListener('mousemove', onDragMove, true);
		addEventListener('mouseup', onRelease, true);
	});
	canvas.addEventListener('mouseup', onRelease);
	canvas.addEventListener('mousemove', event => {
		lastPointer = pointer(event);
		if (!dragging) updateHover();
	});
	canvas.addEventListener('mouseleave', () => { if (!dragging) { hover = 0; path = []; tip.hidden = true; draw(); } });
	api.cleanup(() => { removeEventListener('mousemove', onDragMove, true); removeEventListener('mouseup', onRelease, true); });
	canvas.addEventListener('contextmenu', event => {
		event.preventDefault();
		lastPointer = pointer(event);
		const id = nodeAt(lastPointer[0], lastPointer[1]);
		if (id && state.alloc.has(id)) refundNode(id);
	});
	canvas.addEventListener('wheel', event => {
		event.preventDefault();
		event.stopPropagation();
		const [sx, sy] = pointer(event);
		const [wx, wy] = toWorld(sx, sy);
		view.zoom = Math.max(0.16, Math.min(3, view.zoom * (event.deltaY < 0 ? 1.12 : 1 / 1.12)));
		view.x = sx - view.w / 2 - wx * view.zoom;
		view.y = sy - view.h / 2 - wy * view.zoom;
		lastPointer = [sx, sy];
		updateHover();
	}, { passive: false });

	function allocate(id) {
		if (busy || owned(id)) return;
		if (!state.start) return say(state.loaded ? 'Choose a first class to wake the tree.' : 'The server has not answered yet. Close and reopen the window.', true);
		const chain = pathTo(id);
		if (!chain) return say('That node cannot be reached.', true);
		const newKeys = chain.filter(c => NODES.get(c).t === 'k').length;
		if (state.keyLimit && newKeys && keystonesUsed() + newKeys > state.keyLimit) return say(`You can take at most ${state.keyLimit} keystone${state.keyLimit > 1 ? 's' : ''}. Refund one first.`, true);
		const wrongLine = chain.map(c => NODES.get(c)).find(n => blocked(n.id));
		if (wrongLine) return say(wrongLine.up ? `That branch is for reborn characters (${wrongLine.ul}).` : `That branch is for the ${wrongLine.req} job line.`, true);
		if (chain.length > unspent()) return say(`That needs ${chain.length} points and you have ${unspent()}.`, true);
		ask(`alloc ${chain.join(',')}`);
	}
	function refundNode(id) {
		if (busy || state.refund < 0) return;
		if (!removable(id)) return say('Other nodes depend on that one: refund the nodes beyond it first.', true);
		ask(`refund ${id}`);
	}

	$('.mode').addEventListener('click', event => { refundMode = !refundMode; event.currentTarget.classList.toggle('on', refundMode); say(refundMode ? 'Refund mode: click an allocated node to take it back.' : ''); });
	$('.fit').addEventListener('click', fit);
	const sideButton = $('.sidebtn');
	const setSide = visible => {
		side.hidden = !visible;
		sideButton.classList.toggle('on', visible);
		try { api.preferences?.set('side', visible); } catch { /* not remembered */ }
		renderSide();
		requestAnimationFrame(resize);
	};
	sideButton.addEventListener('click', () => setSide(side.hidden));
	let sideStart = true;
	try { sideStart = api.preferences?.get('side', true) !== false; } catch { /* default */ }
	side.hidden = !sideStart;
	sideButton.classList.toggle('on', sideStart);
	$('.reset').addEventListener('click', event => {
		const button = event.currentTarget;
		if (!state.alloc.size) return say('Nothing is allocated.');
		if (Date.now() > resetArmed) {
			resetArmed = Date.now() + 4000;
			button.classList.add('warn');
			button.textContent = `Really? (${(state.refund * state.alloc.size).toLocaleString()} zeny)`;
			setTimeout(() => { button.classList.remove('warn'); button.textContent = 'Reset all'; }, 4000);
			return;
		}
		resetArmed = 0;
		button.classList.remove('warn');
		button.textContent = 'Reset all';
		ask('reset');
	});

	const observer = new ResizeObserver(() => resize());
	observer.observe(canvas);
	api.cleanup(() => observer.disconnect());

	const open = () => {
		win.show();
		requestAnimationFrame(() => { resize(); if (!state.loaded) fit(); say(''); ask('state'); });
	};

	// ---- opening it: the @passive command, Alt+P, the button ----
	api.on('server:event', ({ command, text }) => { if (command === 'passive' && text === 'open') { win.isOpen() ? ask('state') : open(); } });

	let inGame = false;
	let launcher = null;
	const setInGame = value => {
		inGame = value;
		launcher?.classList.toggle('ingame', value);
		if (!value && win.isOpen()) win.hide();
	};
	api.on('map:enter', () => setInGame(true), { replay: true });
	api.on('map:leave', () => setInGame(false));

	const onKey = event => {
		if (!inGame || !event.altKey || event.code !== 'KeyP') return;
		event.preventDefault();
		if (win.isOpen()) win.hide(); else open();
	};
	addEventListener('keydown', onKey, true);
	api.cleanup(() => removeEventListener('keydown', onKey, true));

	if (parameters?.show_button !== false) {
		const host = document.createElement('div');
		const root = host.attachShadow({ mode: 'open' });
		root.innerHTML = `<style>${STYLE}</style><button class="launcher${inGame ? ' ingame' : ''}" title="Passive Tree (Alt+P)">PT</button>`;
		launcher = root.querySelector('button');
		launcher.addEventListener('mousedown', event => event.stopImmediatePropagation());
		launcher.addEventListener('click', () => { if (win.isOpen()) win.hide(); else open(); });
		document.body.appendChild(host);
		api.cleanup(() => host.remove());
	}

	say('');
}
